/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using search.Client;
using search.Api;
// uncomment below to import models
//using search.Model;

namespace search.Test.Api
{
    /// <summary>
    ///  Class for testing SearchApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SearchApiTests : IDisposable
    {
        private SearchApi instance;

        public SearchApiTests()
        {
            instance = new SearchApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SearchApi
            //Assert.IsType<SearchApi>(instance);
        }

        /// <summary>
        /// Test SearchConfiguration
        /// </summary>
        [Fact]
        public void SearchConfigurationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SearchConfigRequest body = null;
            //var response = instance.SearchConfiguration(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test SearchDelete
        /// </summary>
        [Fact]
        public void SearchDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SearchDeleteRequest body = null;
            //var response = instance.SearchDelete(body);
            //Assert.IsType<SearchDeleteResponse>(response);
        }

        /// <summary>
        /// Test SearchInsertOrReplace
        /// </summary>
        [Fact]
        public void SearchInsertOrReplaceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SearchWriteRequest body = null;
            //var response = instance.SearchInsertOrReplace(body);
            //Assert.IsType<SearchWriteResponse>(response);
        }

        /// <summary>
        /// Test SearchMSearch
        /// </summary>
        [Fact]
        public void SearchMSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SearchQueryRequest body = null;
            //var response = instance.SearchMSearch(body);
            //Assert.IsType<SearchQueryResponse>(response);
        }

        /// <summary>
        /// Test SearchUpdate
        /// </summary>
        [Fact]
        public void SearchUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SearchWriteRequest body = null;
            //var response = instance.SearchUpdate(body);
            //Assert.IsType<SearchWriteResponse>(response);
        }
    }
}
