/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = search.Client.OpenAPIDateConverter;

namespace search.Model
{
    /// <summary>
    /// contains all the necessary to create or update an index
    /// </summary>
    [DataContract(Name = "searchConfigRequest")]
    public partial class SearchConfigRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchConfigRequest" /> class.
        /// </summary>
        /// <param name="tenantId">tenant_id for which create or update indexes configuration [#DOCGENBUG REQUIRED FIELD].</param>
        /// <param name="configSchema">contains index configurations fields [#DOCGENBUG REQUIRED FIELD].</param>
        public SearchConfigRequest(string tenantId = default(string), List<SearchConfigSchema> configSchema = default(List<SearchConfigSchema>))
        {
            this.TenantId = tenantId;
            this.ConfigSchema = configSchema;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// tenant_id for which create or update indexes configuration [#DOCGENBUG REQUIRED FIELD]
        /// </summary>
        /// <value>tenant_id for which create or update indexes configuration [#DOCGENBUG REQUIRED FIELD]</value>
        [DataMember(Name = "tenantId", EmitDefaultValue = false)]
        public string TenantId { get; set; }

        /// <summary>
        /// contains index configurations fields [#DOCGENBUG REQUIRED FIELD]
        /// </summary>
        /// <value>contains index configurations fields [#DOCGENBUG REQUIRED FIELD]</value>
        [DataMember(Name = "configSchema", EmitDefaultValue = false)]
        public List<SearchConfigSchema> ConfigSchema { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchConfigRequest {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  ConfigSchema: ").Append(ConfigSchema).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
