/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = search.Client.OpenAPIDateConverter;

namespace search.Model
{
    /// <summary>
    /// Defines searchParamFilterType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SearchParamFilterType
    {
        /// <summary>
        /// Enum TERM for value: TERM
        /// </summary>
        [EnumMember(Value = "TERM")]
        TERM = 1,

        /// <summary>
        /// Enum TERMS for value: TERMS
        /// </summary>
        [EnumMember(Value = "TERMS")]
        TERMS = 2,

        /// <summary>
        /// Enum RANGE for value: RANGE
        /// </summary>
        [EnumMember(Value = "RANGE")]
        RANGE = 3
    }

}
