/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = search.Client.OpenAPIDateConverter;

namespace search.Model
{
    /// <summary>
    /// Defines searchConfigSchemaAttributeType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SearchConfigSchemaAttributeType
    {
        /// <summary>
        /// Enum TEXT for value: TEXT
        /// </summary>
        [EnumMember(Value = "TEXT")]
        TEXT = 1,

        /// <summary>
        /// Enum BOOLEAN for value: BOOLEAN
        /// </summary>
        [EnumMember(Value = "BOOLEAN")]
        BOOLEAN = 2,

        /// <summary>
        /// Enum INTEGER for value: INTEGER
        /// </summary>
        [EnumMember(Value = "INTEGER")]
        INTEGER = 3,

        /// <summary>
        /// Enum FLOAT for value: FLOAT
        /// </summary>
        [EnumMember(Value = "FLOAT")]
        FLOAT = 4,

        /// <summary>
        /// Enum DATE for value: DATE
        /// </summary>
        [EnumMember(Value = "DATE")]
        DATE = 5,

        /// <summary>
        /// Enum OBJECT for value: OBJECT
        /// </summary>
        [EnumMember(Value = "OBJECT")]
        OBJECT = 6
    }

}
