/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = search.Client.OpenAPIDateConverter;

namespace search.Model
{
    /// <summary>
    /// SearchDeleteRequest
    /// </summary>
    [DataContract(Name = "searchDeleteRequest")]
    public partial class SearchDeleteRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchDeleteRequest" /> class.
        /// </summary>
        /// <param name="tenantId">tenant_id for which remove costraints [#DOCGENBUG REQUIRED FIELD].</param>
        /// <param name="constraints">constraints to remove (index name) [#DOCGENBUG REQUIRED FIELD].</param>
        public SearchDeleteRequest(string tenantId = default(string), List<SearchDeleteConstraints> constraints = default(List<SearchDeleteConstraints>))
        {
            this.TenantId = tenantId;
            this.Constraints = constraints;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// tenant_id for which remove costraints [#DOCGENBUG REQUIRED FIELD]
        /// </summary>
        /// <value>tenant_id for which remove costraints [#DOCGENBUG REQUIRED FIELD]</value>
        [DataMember(Name = "tenantId", EmitDefaultValue = false)]
        public string TenantId { get; set; }

        /// <summary>
        /// constraints to remove (index name) [#DOCGENBUG REQUIRED FIELD]
        /// </summary>
        /// <value>constraints to remove (index name) [#DOCGENBUG REQUIRED FIELD]</value>
        [DataMember(Name = "constraints", EmitDefaultValue = false)]
        public List<SearchDeleteConstraints> Constraints { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchDeleteRequest {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  Constraints: ").Append(Constraints).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
