/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using search.Model;
using search.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace search.Test.Model
{
    /// <summary>
    ///  Class for testing ParamSortOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParamSortOrderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ParamSortOrder
        //private ParamSortOrder instance;

        public ParamSortOrderTests()
        {
            // TODO uncomment below to create an instance of ParamSortOrder
            //instance = new ParamSortOrder();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ParamSortOrder
        /// </summary>
        [Fact]
        public void ParamSortOrderInstanceTest()
        {
            // TODO uncomment below to test "IsType" ParamSortOrder
            //Assert.IsType<ParamSortOrder>(instance);
        }
    }
}
