/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using search.Model;
using search.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace search.Test.Model
{
    /// <summary>
    ///  Class for testing SearchConfigRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchConfigRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchConfigRequest
        //private SearchConfigRequest instance;

        public SearchConfigRequestTests()
        {
            // TODO uncomment below to create an instance of SearchConfigRequest
            //instance = new SearchConfigRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchConfigRequest
        /// </summary>
        [Fact]
        public void SearchConfigRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchConfigRequest
            //Assert.IsType<SearchConfigRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ConfigSchema'
        /// </summary>
        [Fact]
        public void ConfigSchemaTest()
        {
            // TODO unit test for the property 'ConfigSchema'
        }
    }
}
