/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using search.Model;
using search.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace search.Test.Model
{
    /// <summary>
    ///  Class for testing SearchConfigSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchConfigSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchConfigSchema
        //private SearchConfigSchema instance;

        public SearchConfigSchemaTests()
        {
            // TODO uncomment below to create an instance of SearchConfigSchema
            //instance = new SearchConfigSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchConfigSchema
        /// </summary>
        [Fact]
        public void SearchConfigSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchConfigSchema
            //Assert.IsType<SearchConfigSchema>(instance);
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'DocumentKeyName'
        /// </summary>
        [Fact]
        public void DocumentKeyNameTest()
        {
            // TODO unit test for the property 'DocumentKeyName'
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }

        /// <summary>
        /// Test the property 'Searchables'
        /// </summary>
        [Fact]
        public void SearchablesTest()
        {
            // TODO unit test for the property 'Searchables'
        }

        /// <summary>
        /// Test the property 'Facets'
        /// </summary>
        [Fact]
        public void FacetsTest()
        {
            // TODO unit test for the property 'Facets'
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }

        /// <summary>
        /// Test the property 'Sortables'
        /// </summary>
        [Fact]
        public void SortablesTest()
        {
            // TODO unit test for the property 'Sortables'
        }
    }
}
