/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using search.Model;
using search.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace search.Test.Model
{
    /// <summary>
    ///  Class for testing SearchDeleteRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchDeleteRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchDeleteRequest
        //private SearchDeleteRequest instance;

        public SearchDeleteRequestTests()
        {
            // TODO uncomment below to create an instance of SearchDeleteRequest
            //instance = new SearchDeleteRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchDeleteRequest
        /// </summary>
        [Fact]
        public void SearchDeleteRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchDeleteRequest
            //Assert.IsType<SearchDeleteRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Constraints'
        /// </summary>
        [Fact]
        public void ConstraintsTest()
        {
            // TODO unit test for the property 'Constraints'
        }
    }
}
