/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using search.Model;
using search.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace search.Test.Model
{
    /// <summary>
    ///  Class for testing SearchParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchParams
        //private SearchParams instance;

        public SearchParamsTests()
        {
            // TODO uncomment below to create an instance of SearchParams
            //instance = new SearchParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchParams
        /// </summary>
        [Fact]
        public void SearchParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchParams
            //Assert.IsType<SearchParams>(instance);
        }

        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

        /// <summary>
        /// Test the property 'Term'
        /// </summary>
        [Fact]
        public void TermTest()
        {
            // TODO unit test for the property 'Term'
        }

        /// <summary>
        /// Test the property 'Searchables'
        /// </summary>
        [Fact]
        public void SearchablesTest()
        {
            // TODO unit test for the property 'Searchables'
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }

        /// <summary>
        /// Test the property 'Facets'
        /// </summary>
        [Fact]
        public void FacetsTest()
        {
            // TODO unit test for the property 'Facets'
        }

        /// <summary>
        /// Test the property 'Sorts'
        /// </summary>
        [Fact]
        public void SortsTest()
        {
            // TODO unit test for the property 'Sorts'
        }

        /// <summary>
        /// Test the property 'MinScore'
        /// </summary>
        [Fact]
        public void MinScoreTest()
        {
            // TODO unit test for the property 'MinScore'
        }
    }
}
