/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using search.Model;
using search.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace search.Test.Model
{
    /// <summary>
    ///  Class for testing SearchAggrMap
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchAggrMapTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchAggrMap
        //private SearchAggrMap instance;

        public SearchAggrMapTests()
        {
            // TODO uncomment below to create an instance of SearchAggrMap
            //instance = new SearchAggrMap();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchAggrMap
        /// </summary>
        [Fact]
        public void SearchAggrMapInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchAggrMap
            //Assert.IsType<SearchAggrMap>(instance);
        }

        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
    }
}
