/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using search.Model;
using search.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace search.Test.Model
{
    /// <summary>
    ///  Class for testing SearchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchResult
        //private SearchResult instance;

        public SearchResultTests()
        {
            // TODO uncomment below to create an instance of SearchResult
            //instance = new SearchResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchResult
        /// </summary>
        [Fact]
        public void SearchResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchResult
            //Assert.IsType<SearchResult>(instance);
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Fact]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }

        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Fact]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }

        /// <summary>
        /// Test the property 'TotalHits'
        /// </summary>
        [Fact]
        public void TotalHitsTest()
        {
            // TODO unit test for the property 'TotalHits'
        }

        /// <summary>
        /// Test the property 'Hits'
        /// </summary>
        [Fact]
        public void HitsTest()
        {
            // TODO unit test for the property 'Hits'
        }

        /// <summary>
        /// Test the property 'Aggregations'
        /// </summary>
        [Fact]
        public void AggregationsTest()
        {
            // TODO unit test for the property 'Aggregations'
        }
    }
}
