/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using search.Model;
using search.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace search.Test.Model
{
    /// <summary>
    ///  Class for testing SearchParamFacetType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchParamFacetTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchParamFacetType
        //private SearchParamFacetType instance;

        public SearchParamFacetTypeTests()
        {
            // TODO uncomment below to create an instance of SearchParamFacetType
            //instance = new SearchParamFacetType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchParamFacetType
        /// </summary>
        [Fact]
        public void SearchParamFacetTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchParamFacetType
            //Assert.IsType<SearchParamFacetType>(instance);
        }
    }
}
