/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using search.Model;
using search.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace search.Test.Model
{
    /// <summary>
    ///  Class for testing SearchParamSort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchParamSortTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchParamSort
        //private SearchParamSort instance;

        public SearchParamSortTests()
        {
            // TODO uncomment below to create an instance of SearchParamSort
            //instance = new SearchParamSort();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchParamSort
        /// </summary>
        [Fact]
        public void SearchParamSortInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchParamSort
            //Assert.IsType<SearchParamSort>(instance);
        }

        /// <summary>
        /// Test the property 'Attribute'
        /// </summary>
        [Fact]
        public void AttributeTest()
        {
            // TODO unit test for the property 'Attribute'
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
    }
}
