/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using search.Model;
using search.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace search.Test.Model
{
    /// <summary>
    ///  Class for testing SearchDeleteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchDeleteResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchDeleteResponse
        //private SearchDeleteResponse instance;

        public SearchDeleteResponseTests()
        {
            // TODO uncomment below to create an instance of SearchDeleteResponse
            //instance = new SearchDeleteResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchDeleteResponse
        /// </summary>
        [Fact]
        public void SearchDeleteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchDeleteResponse
            //Assert.IsType<SearchDeleteResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }
}
