/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using search.Model;
using search.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace search.Test.Model
{
    /// <summary>
    ///  Class for testing SearchConfigSchemaAttribute
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchConfigSchemaAttributeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchConfigSchemaAttribute
        //private SearchConfigSchemaAttribute instance;

        public SearchConfigSchemaAttributeTests()
        {
            // TODO uncomment below to create an instance of SearchConfigSchemaAttribute
            //instance = new SearchConfigSchemaAttribute();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchConfigSchemaAttribute
        /// </summary>
        [Fact]
        public void SearchConfigSchemaAttributeInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchConfigSchemaAttribute
            //Assert.IsType<SearchConfigSchemaAttribute>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
    }
}
