/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using search.Model;
using search.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace search.Test.Model
{
    /// <summary>
    ///  Class for testing SearchWriteError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchWriteErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchWriteError
        //private SearchWriteError instance;

        public SearchWriteErrorTests()
        {
            // TODO uncomment below to create an instance of SearchWriteError
            //instance = new SearchWriteError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchWriteError
        /// </summary>
        [Fact]
        public void SearchWriteErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchWriteError
            //Assert.IsType<SearchWriteError>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'DocumentKeyName'
        /// </summary>
        [Fact]
        public void DocumentKeyNameTest()
        {
            // TODO unit test for the property 'DocumentKeyName'
        }

        /// <summary>
        /// Test the property 'DocumentKeyValue'
        /// </summary>
        [Fact]
        public void DocumentKeyValueTest()
        {
            // TODO unit test for the property 'DocumentKeyValue'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
