/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using search.Model;
using search.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace search.Test.Model
{
    /// <summary>
    ///  Class for testing SearchDeleteConstraints
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchDeleteConstraintsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchDeleteConstraints
        //private SearchDeleteConstraints instance;

        public SearchDeleteConstraintsTests()
        {
            // TODO uncomment below to create an instance of SearchDeleteConstraints
            //instance = new SearchDeleteConstraints();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchDeleteConstraints
        /// </summary>
        [Fact]
        public void SearchDeleteConstraintsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchDeleteConstraints
            //Assert.IsType<SearchDeleteConstraints>(instance);
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
    }
}
