/*
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using search.Model;
using search.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace search.Test.Model
{
    /// <summary>
    ///  Class for testing SearchPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchPayload
        //private SearchPayload instance;

        public SearchPayloadTests()
        {
            // TODO uncomment below to create an instance of SearchPayload
            //instance = new SearchPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchPayload
        /// </summary>
        [Fact]
        public void SearchPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchPayload
            //Assert.IsType<SearchPayload>(instance);
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Fact]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }
    }
}
